//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.13 at 12:51:56 PM EDT 
//


package yoh.xsd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for expectedDBChange complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="expectedDBChange">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.yohahnandcompany.com/testCase}expectedOutput">
 *       &lt;sequence>
 *         &lt;element name="dbChange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "expectedDBChange", propOrder = {
    "dbChange"
})
public class ExpectedDBChange
    extends ExpectedOutput
{

    @XmlElement(required = true)
    protected String dbChange;

    /**
     * Gets the value of the dbChange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbChange() {
        return dbChange;
    }

    /**
     * Sets the value of the dbChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbChange(String value) {
        this.dbChange = value;
    }

}
