//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.13 at 12:51:56 PM EDT 
//


package yoh.xsd.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the yoh.xsd.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TestCase_QNAME = new QName("http://www.yohahnandcompany.com/testCase", "testCase");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: yoh.xsd.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TestCase }
     * 
     */
    public TestCase createTestCase() {
        return new TestCase();
    }

    /**
     * Create an instance of {@link TestStep }
     * 
     */
    public TestStep createTestStep() {
        return new TestStep();
    }

    /**
     * Create an instance of {@link ExpectedDBChange }
     * 
     */
    public ExpectedDBChange createExpectedDBChange() {
        return new ExpectedDBChange();
    }

    /**
     * Create an instance of {@link InputMessage }
     * 
     */
    public InputMessage createInputMessage() {
        return new InputMessage();
    }

    /**
     * Create an instance of {@link ExpectedMessage }
     * 
     */
    public ExpectedMessage createExpectedMessage() {
        return new ExpectedMessage();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TestCase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.yohahnandcompany.com/testCase", name = "testCase")
    public JAXBElement<TestCase> createTestCase(TestCase value) {
        return new JAXBElement<TestCase>(_TestCase_QNAME, TestCase.class, null, value);
    }

}
